name: giga_secretary
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  just_audio: ^0.9.36
  audio_session: ^0.1.18
  file_picker: ^9.0.0
  googleapis: ^11.0.0
  googleapis_auth: ^1.4.1
  google_sign_in: ^6.1.6
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.2
  audioplayers: ^5.2.1
  video_player: ^2.8.2
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/GSLOGO.svg
